Repository DIT112-V19/group-05, pull requests merged in 2019-05, with the labels that each got.

#40 Features/control car
  android/app/src/main/java/com/example/hajken/CanvasView.java
  android/app/src/main/java/com/example/hajken/CoordinateConverter.java
  android/app/src/main/java/com/example/hajken/DrawFragment.java
  android/app/src/main/java/com/example/hajken/MathUtility.java
Labels: Sprint #3, Sprint #4, USER STORY 5

#43 Features/input to array
  arduino/src/hajkenCar/hajkenCar.ino
Labels: Sprint #3

#44 Features/design route
  android/app/src/main/java/com/example/hajken/CoordinateConverter.java
  android/app/src/main/java/com/example/hajken/DrawFragment.java
  android/app/src/main/java/com/example/hajken/MathUtility.java
Labels: Sprint #4, USER STORY 5

#53 Features/design route
  android/app/src/main/java/com/example/hajken/CanvasView.java
  android/app/src/main/java/com/example/hajken/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/CoordinateConverter.java
  android/app/src/main/java/com/example/hajken/CustomDialogFragment.java
  android/app/src/main/java/com/example/hajken/DrawFragment.java
  android/app/src/main/java/com/example/hajken/GatewayFragment.java
  android/app/src/main/java/com/example/hajken/MathUtility.java
  android/app/src/main/res/layout/fragment_gateway.xml
Labels: Sprint #4

#54 Subject: Vector mathmatics and receive command/reverse commands
  .travis.yml
  android/app/build.gradle
  android/app/debug/app-debug.apk
  android/app/debug/output.json
  android/app/src/main/java/com/example/hajken/BluetoothConnection.java
  android/app/src/main/java/com/example/hajken/CanvasView.java
  android/app/src/main/java/com/example/hajken/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/CoordinateConverter.java
  android/app/src/main/java/com/example/hajken/CustomDialogFragment.java
  android/app/src/main/java/com/example/hajken/DrawFragment.java
  android/app/src/main/java/com/example/hajken/GatewayFragment.java
  android/app/src/main/java/com/example/hajken/MathUtility.java
  android/app/src/main/java/com/example/hajken/RecyclerViewAdapter.java
  android/app/src/main/java/com/example/hajken/ScanFragment.java
  android/app/src/main/res/drawable/button.xml
  android/app/src/main/res/drawable/button_background.xml
  android/app/src/main/res/drawable/gradient.xml
  android/app/src/main/res/layout/fragment_collection.xml
  android/app/src/main/res/layout/fragment_draw.xml
  android/app/src/main/res/layout/fragment_gateway.xml
  android/app/src/main/res/layout/fragment_scan.xml
  android/app/src/main/res/layout/fragment_start.xml
  android/app/src/main/res/layout/recycler_item.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  arduino/src/hajkenCar/hajkenCar.ino
Labels: Sprint #3, Sprint #4

#57 Subject: Add Google Maps Fragment
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/hajken/BluetoothConnection.java
  android/app/src/main/java/com/example/hajken/GatewayFragment.java
  android/app/src/main/java/com/example/hajken/GoogleMapsFragment.java
  android/app/src/main/java/com/example/hajken/MainActivity.java
  android/app/src/main/java/com/example/hajken/StartFragment.java
  android/app/src/main/res/layout/fragment_gateway.xml
  android/app/src/main/res/layout/fragment_google_maps.xml
  android/app/src/main/res/layout/fragment_start.xml
  android/app/src/main/res/values/strings.xml
  android/gradle.properties
  arduino/src/hajkenCar/hajkenCar.ino
Labels: Sprint #5, USER STORY 6

#67 Features/design route
  android/app/src/main/java/com/example/hajken/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/CoordinateConverter.java
  android/app/src/main/java/com/example/hajken/DrawFragment.java
  android/app/src/main/java/com/example/hajken/MainActivity.java
  android/app/src/main/java/com/example/hajken/MathUtility.java
  android/app/src/main/java/com/example/hajken/ScanFragment.java
  android/app/src/main/java/com/example/hajken/StartFragment.java
  android/app/src/main/res/drawable/button.xml
  android/app/src/main/res/layout/dialog_custom.xml
  android/app/src/main/res/layout/fragment_collection.xml
  android/app/src/main/res/layout/fragment_draw.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: Sprint #5, USER STORY 1

#68 Subject: Add button state adaptation, packaging of files
  android/app/build.gradle
  android/app/src/main/java/com/example/hajken/MainActivity.java
  android/app/src/main/java/com/example/hajken/bluetooth/Bluetooth.java
  android/app/src/main/java/com/example/hajken/bluetooth/BluetoothConnection.java
  android/app/src/main/java/com/example/hajken/fragments/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/fragments/CoordinateConverter.java
  android/app/src/main/java/com/example/hajken/fragments/DrawFragment.java
  android/app/src/main/java/com/example/hajken/fragments/GatewayFragment.java
  android/app/src/main/java/com/example/hajken/fragments/GoogleMapsFragment.java
  android/app/src/main/java/com/example/hajken/fragments/ScanFragment.java
  android/app/src/main/java/com/example/hajken/fragments/StartFragment.java
  android/app/src/main/java/com/example/hajken/helpers/CanvasView.java
  android/app/src/main/java/com/example/hajken/helpers/CustomDialogFragment.java
  android/app/src/main/java/com/example/hajken/helpers/ListAdapter.java
  android/app/src/main/java/com/example/hajken/helpers/ListOfDevices.java
  android/app/src/main/java/com/example/hajken/helpers/MathUtility.java
  android/app/src/main/java/com/example/hajken/helpers/OurData.java
  android/app/src/main/java/com/example/hajken/helpers/RecyclerItemClickListener.java
  android/app/src/main/res/drawable/bluetooth_symbol.png
  android/app/src/main/res/drawable/button.xml
  android/app/src/main/res/drawable/button_background.xml
  android/app/src/main/res/drawable/button_text_color.xml
  android/app/src/main/res/drawable/circular_shape.xml
  android/app/src/main/res/drawable/device_list.xml
  android/app/src/main/res/drawable/radar_symbol.png
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_draw.xml
  android/app/src/main/res/layout/fragment_gateway.xml
  android/app/src/main/res/layout/fragment_google_maps.xml
  android/app/src/main/res/layout/fragment_scan.xml
  android/app/src/main/res/layout/fragment_start.xml
  android/app/src/main/res/layout/listview_item.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: Sprint #5, UI-Design

#71 Features/direction correction
  arduino/src/hajkenCar/hajkenCar.ino
Labels: Sprint #4

#72 Subject: Fix buttons
  android/app/src/main/java/com/example/hajken/fragments/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/fragments/DrawFragment.java
  android/app/src/main/java/com/example/hajken/fragments/GoogleMapsFragment.java
  android/app/src/main/java/com/example/hajken/fragments/ScanFragment.java
  android/app/src/main/res/layout/fragment_collection.xml
  android/app/src/main/res/layout/fragment_draw.xml
  android/app/src/main/res/layout/fragment_google_maps.xml
  android/app/src/main/res/values/strings.xml
Labels: UI-Design

#75 Subject: Add horizontal radio group and seekbar
  android/app/build.gradle
  android/app/src/main/java/com/example/hajken/MainActivity.java
  android/app/src/main/java/com/example/hajken/bluetooth/BluetoothConnection.java
  android/app/src/main/java/com/example/hajken/fragments/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/fragments/DrawFragment.java
  android/app/src/main/java/com/example/hajken/fragments/GatewayFragment.java
  android/app/src/main/java/com/example/hajken/fragments/GoogleMapsFragment.java
  android/app/src/main/java/com/example/hajken/helpers/CoordinateConverter.java
  android/app/src/main/res/layout/fragment_draw.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
Labels: Sprint #4, TASK

#76 Subject: Add Listener for button states, dialog fragment after you draw
  android/app/src/main/java/com/example/hajken/bluetooth/BluetoothConnection.java
  android/app/src/main/java/com/example/hajken/fragments/DrawFragment.java
  android/app/src/main/java/com/example/hajken/fragments/ScanFragment.java
  android/app/src/main/res/layout/listview_item.xml
  android/build.gradle
  android/gradle/wrapper/gradle-wrapper.properties
Labels: Sprint #4

#77 Subject: Borders to UI
  android/app/src/main/java/com/example/hajken/fragments/DrawFragment.java
  android/app/src/main/res/drawable/border.xml
  android/app/src/main/res/layout/fragment_draw.xml
  android/app/src/main/res/values/strings.xml
Labels: Sprint #4, TASK, UI-Design

#80 Subject: Add seekbar and radiogroup
  android/app/src/main/java/com/example/hajken/fragments/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/fragments/DrawFragment.java
  android/app/src/main/java/com/example/hajken/fragments/GatewayFragment.java
  android/app/src/main/java/com/example/hajken/fragments/GoogleMapsFragment.java
  android/app/src/main/res/layout/fragment_collection.xml
  android/app/src/main/res/layout/fragment_draw.xml
  android/app/src/main/res/layout/fragment_gateway.xml
  android/app/src/main/res/layout/fragment_google_maps.xml
  android/app/src/main/res/layout/fragment_scan.xml
  android/app/src/main/res/layout/list_item.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
Labels: Sprint #5, TASK

#90 Subject: Add automatic saving of drawings
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/hajken/InterfaceMainActivity.java
  android/app/src/main/java/com/example/hajken/MainActivity.java
  android/app/src/main/java/com/example/hajken/bluetooth/Bluetooth.java
  android/app/src/main/java/com/example/hajken/bluetooth/BluetoothConnection.java
  android/app/src/main/java/com/example/hajken/fragments/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/fragments/DrawFragment.java
  android/app/src/main/java/com/example/hajken/fragments/GatewayFragment.java
  android/app/src/main/java/com/example/hajken/fragments/GoogleMapsFragment.java
  android/app/src/main/java/com/example/hajken/fragments/ScanFragment.java
  android/app/src/main/java/com/example/hajken/fragments/StartFragment.java
  android/app/src/main/java/com/example/hajken/helpers/CanvasView.java
  android/app/src/main/java/com/example/hajken/helpers/CoordinateConverter.java
  android/app/src/main/java/com/example/hajken/helpers/CoordinatesHolder.java
  android/app/src/main/java/com/example/hajken/helpers/CoordinatesListItem.java
  android/app/src/main/java/com/example/hajken/helpers/ListAdapter.java
  android/app/src/main/java/com/example/hajken/helpers/OurData.java
  android/app/src/main/res/drawable/border.xml
  android/app/src/main/res/drawable/button.xml
  android/app/src/main/res/drawable/button_text_color.xml
  android/app/src/main/res/drawable/circular_shape.xml
  android/app/src/main/res/drawable/device_list.xml
  android/app/src/main/res/layout/fragment_collection.xml
  android/app/src/main/res/layout/fragment_draw.xml
  android/app/src/main/res/layout/fragment_gateway.xml
  android/app/src/main/res/layout/fragment_google_maps.xml
  android/app/src/main/res/layout/fragment_scan.xml
  android/app/src/main/res/layout/fragment_start.xml
  android/app/src/main/res/layout/list_item.xml
  android/app/src/main/res/layout/listview_item.xml
  android/app/src/main/res/layout/recycler_item.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
Labels: TASK, USER STORY 9

#91 Subject: Add startPoint and display of actual route
  android/app/src/main/java/com/example/hajken/MainActivity.java
  android/app/src/main/java/com/example/hajken/fragments/DrawFragment.java
  android/app/src/main/java/com/example/hajken/fragments/ScanFragment.java
  android/app/src/main/java/com/example/hajken/helpers/CanvasView.java
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: Sprint #5, UI-Design

#92 Subject: Add app icon
  android/app/src/main/ic_launcher-web.png
  android/app/src/main/java/com/example/hajken/fragments/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/helpers/OurData.java
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
Labels: TASK, UI-Design

#93 Subject: Add dialog window to collection fragment
  android/app/src/main/java/com/example/hajken/fragments/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/fragments/DrawFragment.java
Labels: USER STORY 9

#74 Features/google maps
  .gitignore
  .travis.yml
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/hajken/MainActivity.java
  android/app/src/main/java/com/example/hajken/fragments/GoogleMapsFragment.java
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/values/strings.xml
  android/build.gradle
  android/gradle.properties.no.git
  arduino/src/hajkenCar/hajkenCar.ino
Labels: Sprint #4, TASK, USER STORY 6

#95 Subject: Add listener for button states
  android/app/src/main/java/com/example/hajken/MainActivity.java
  android/app/src/main/java/com/example/hajken/bluetooth/Bluetooth.java
  android/app/src/main/java/com/example/hajken/bluetooth/BluetoothConnection.java
  android/app/src/main/java/com/example/hajken/fragments/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/fragments/DrawFragment.java
  android/app/src/main/java/com/example/hajken/fragments/GoogleMapsFragment.java
  android/app/src/main/java/com/example/hajken/fragments/ScanFragment.java
  android/app/src/main/java/com/example/hajken/helpers/ListAdapter.java
Labels: TASK

#99 Features/google maps
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/hajken/MainActivity.java
  android/app/src/main/java/com/example/hajken/fragments/GoogleMapsFragment.java
  android/app/src/main/java/com/example/hajken/helpers/GPSConnector.java
  android/app/src/main/java/com/example/hajken/helpers/GPSTracker.java
Labels: Sprint #6, TASK, USER STORY 6

#102 Features/refactor bluetooth
  android/app/src/main/java/com/example/hajken/InterfaceMainActivity.java
  android/app/src/main/java/com/example/hajken/MainActivity.java
  android/app/src/main/java/com/example/hajken/bluetooth/BluetoothConnection.java
  android/app/src/main/java/com/example/hajken/fragments/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/fragments/DrawFragment.java
  android/app/src/main/java/com/example/hajken/fragments/GatewayFragment.java
  android/app/src/main/java/com/example/hajken/fragments/ScanFragment.java
  android/app/src/main/java/com/example/hajken/helpers/CanvasView.java
Labels: TASK

#103 Features/save routes
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/hajken/bluetooth/BluetoothConnection.java
  android/app/src/main/java/com/example/hajken/fragments/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/fragments/DrawFragment.java
  android/app/src/main/java/com/example/hajken/helpers/CoordinatesHolder.java
  android/app/src/main/java/com/example/hajken/helpers/CoordinatesListItem.java
  android/app/src/main/java/com/example/hajken/helpers/ListAdapter.java
  android/app/src/main/java/com/example/hajken/helpers/SaveData.java
  android/app/src/main/res/layout/fragment_draw.xml
Labels: Sprint #6, TASK, USER STORY 9

#104 Subject: Add Highlight on selected item
  android/app/src/main/java/com/example/hajken/helpers/ListAdapter.java
Labels: TASK, UI-Design

#105 Features/pcb adjusting
  arduino/src/hajkenCar/hajkenCar.ino
Labels: Sprint #6

#111 Features/google maps
  android/app/src/main/java/com/example/hajken/MainActivity.java
  android/app/src/main/java/com/example/hajken/bluetooth/BluetoothConnection.java
  android/app/src/main/java/com/example/hajken/fragments/GatewayFragment.java
  android/app/src/main/java/com/example/hajken/fragments/GoogleMapsFragment.java
  android/app/src/main/java/com/example/hajken/helpers/GPSConnector.java
  android/app/src/main/java/com/example/hajken/helpers/GPSTracker.java
Labels: Sprint #6, TASK, USER STORY 6

#112 Features/google maps
  android/app/src/main/java/com/example/hajken/fragments/GoogleMapsFragment.java
  android/app/src/main/java/com/example/hajken/helpers/GPSTracker.java
Labels: Sprint #7, USER STORY 6

#113 Features/internal flow
  arduino/src/hajkenCar/hajkenCar.ino
Labels: Sprint #6, Sprint #7

#114 Subject: Refactor and bluetooth adaptivity
  android/app/build.gradle
  android/app/src/androidTest/java/com/example/hajken/ExampleInstrumentedTest.java
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/example/hajken/InterfaceMainActivity.java
  android/app/src/main/java/com/example/hajken/MainActivity.java
  android/app/src/main/java/com/example/hajken/bluetooth/Bluetooth.java
  android/app/src/main/java/com/example/hajken/bluetooth/BluetoothConnection.java
  android/app/src/main/java/com/example/hajken/bluetooth/ConnectionListener.java
  android/app/src/main/java/com/example/hajken/bluetooth/VehicleListener.java
  android/app/src/main/java/com/example/hajken/fragments/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/fragments/DrawFragment.java
  android/app/src/main/java/com/example/hajken/fragments/GatewayFragment.java
  android/app/src/main/java/com/example/hajken/fragments/GoogleMapsFragment.java
  android/app/src/main/java/com/example/hajken/fragments/ScanFragment.java
  android/app/src/main/java/com/example/hajken/fragments/StartFragment.java
  android/app/src/main/java/com/example/hajken/helpers/CanvasView.java
  android/app/src/main/java/com/example/hajken/helpers/CoordinateConverter.java
  android/app/src/main/java/com/example/hajken/helpers/CoordinatesHolder.java
  android/app/src/main/java/com/example/hajken/helpers/CoordinatesListItem.java
  android/app/src/main/java/com/example/hajken/helpers/CustomDialogFragment.java
  android/app/src/main/java/com/example/hajken/helpers/GPSTracker.java
  android/app/src/main/java/com/example/hajken/helpers/ListAdapter.java
  android/app/src/main/java/com/example/hajken/helpers/ListOfDevices.java
  android/app/src/main/java/com/example/hajken/helpers/MathUtility.java
  android/app/src/main/java/com/example/hajken/helpers/OurData.java
  android/app/src/main/java/com/example/hajken/helpers/RecyclerItemClickListener.java
  android/app/src/main/res/drawable/border_btn.xml
  android/app/src/main/res/drawable/border_dialog.xml
  android/app/src/main/res/drawable/btn_general.xml
  android/app/src/main/res/drawable/btn_text_color.xml
  android/app/src/main/res/drawable/cat_symbol.jpg
  android/app/src/main/res/drawable/circle_symbol.png
  android/app/src/main/res/drawable/shape_circular.xml
  android/app/src/main/res/drawable/square_symbol.png
  android/app/src/main/res/drawable/triangle_symbol.png
  android/app/src/main/res/drawable/vehicle_symbol.png
  android/app/src/main/res/drawable/z_symbol.png
  android/app/src/main/res/layout/dialog_custom.xml
  android/app/src/main/res/layout/fragment_collection.xml
  android/app/src/main/res/layout/fragment_draw.xml
  android/app/src/main/res/layout/fragment_gateway.xml
  android/app/src/main/res/layout/fragment_google_maps.xml
  android/app/src/main/res/layout/fragment_scan.xml
  android/app/src/main/res/layout/fragment_start.xml
  android/app/src/main/res/layout/recycler_item.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: Sprint #6, Sprint #7, TASK, UI-Design

#115 Features/refactor arduino
  arduino/src/hajkenCar/hajkenCar.ino
  pcb/hajken_cutouts_v1/smartcar_shield_cutouts.brd
  pcb/hajken_cutouts_v1/smartcar_shield_cutouts.sch
  pcb/hajken_cutouts_v2/smartcar_shield_cutouts.brd
  pcb/hajken_cutouts_v2/smartcar_shield_cutouts.sch
  pcb/hajken_cutouts_v2/smartcar_shield_cutouts_v2-back.png
  pcb/hajken_cutouts_v2/smartcar_shield_cutouts_v2-front.png
Labels: Sprint #7

#116 Finalize readme
  README.md
  android/app/build.gradle
  images/Interface_Part1.gif
  images/Interface_Part2.gif
  images/Interface_Part3.gif
  images/hardware-setup.png
  images/settings-appPermissions.png
  images/settings-localPermissions.png
  images/settings.png
Labels: TASK

#117 Finalize readme
  README.md
  images/YouTubeLink.png
  pcb/hajken_cutouts/smartcar_shield_cutouts.brd
  pcb/hajken_cutouts/smartcar_shield_cutouts.sch
Labels: TASK

#118 Finalize readme
  README.md
Labels: Sprint #7
