Repository DIT112-V19/group-05, pull requests merged in 2019-04, with the labels that each got.

#15 Add pull request template
  config/ISSUE_TEMPLATE.md
  config/PULL_REQUEST_TEMPLATE.md
  config/commit-message.txt
Labels: Sprint #1

#30 Fix button-states and toast-messages
  android/app/src/main/java/com/example/hajken/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/CustomDialogFragment.java
  android/app/src/main/java/com/example/hajken/DrawFragment.java
  android/app/src/main/java/com/example/hajken/GatewayFragment.java
  android/app/src/main/java/com/example/hajken/InterfaceMainActivity.java
  android/app/src/main/java/com/example/hajken/MainActivity.java
  android/app/src/main/java/com/example/hajken/ScanFragment.java
  android/app/src/main/java/com/example/hajken/StartFragment.java
  android/app/src/main/res/layout/fragment_scan.xml
Labels: Sprint #2

#33 Features/design route
  android/app/src/main/java/com/example/hajken/CanvasView.java
  android/app/src/main/java/com/example/hajken/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/CustomDialogFragment.java
  android/app/src/main/java/com/example/hajken/DrawFragment.java
  android/app/src/main/java/com/example/hajken/GatewayFragment.java
  android/app/src/main/java/com/example/hajken/MathUtility.java
  android/app/src/main/java/com/example/hajken/ScanFragment.java
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_draw.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
Labels: Sprint #3

#34 Features/predetermined route
  arduino/src/hajkenCar/hajkenCar.ino
Labels: Sprint #2

#36 Bluetooth connectivity, predetermined routes, route data and input
  android/app/src/main/java/com/example/hajken/Bluetooth.java
  android/app/src/main/java/com/example/hajken/BluetoothConnection.java
  android/app/src/main/java/com/example/hajken/CanvasView.java
  android/app/src/main/java/com/example/hajken/CollectionFragment.java
  android/app/src/main/java/com/example/hajken/CustomDialogFragment.java
  android/app/src/main/java/com/example/hajken/DrawFragment.java
  android/app/src/main/java/com/example/hajken/GatewayFragment.java
  android/app/src/main/java/com/example/hajken/InterfaceMainActivity.java
  android/app/src/main/java/com/example/hajken/MainActivity.java
  android/app/src/main/java/com/example/hajken/MathUtility.java
  android/app/src/main/java/com/example/hajken/ScanFragment.java
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_draw.xml
  android/app/src/main/res/layout/listview_item.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  arduino/src/hajkenCar/hajkenCar.ino
Labels: Sprint #1, Sprint #2, Sprint #3
